Repository Slimefun/Slimefun4, pull requests merged in 2020-10, with the labels that each got.

#2370 Made Necrotic Skull unplaceable
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: Hacktoberfest

#2376 Attempt to fix bug #2360
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java
Labels: Hacktoberfest

#2374 Update GrapplingHookListener
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/GrapplingHookListener.java
Labels: Hacktoberfest

#2371 Added seasonal categories to the Cheat Sheet
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/ChestSlimefunGuide.java
Labels: Hacktoberfest

#2379 Add Talisman of the Caveman
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/resources/languages/messages_en.yml
  src/main/resources/languages/researches_en.yml
Labels: Hacktoberfest

#2377 Cartography Table fix
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java
  src/main/resources/languages/messages_en.yml
  src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestVanillaMachinesListener.java
Labels: Hacktoberfest

#2378 Add remaining carat golds to ore crusher
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
Labels: Hacktoberfest

#2385 Speed can affect enchanter/disenchanter times, fixed pom typo
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoDisenchanter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoEnchanter.java
Labels: Hacktoberfest

#2383 Added SlimefunGuideOpenEvent.
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/SlimefunGuideOpenEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunGuideListener.java
Labels: Hacktoberfest

#2386 Define a constant instead of duplicating "backpacks."
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerBackpack.java
Labels: Hacktoberfest

#2392 updated wiki.json
  src/main/resources/wiki.json
Labels: Hacktoberfest

#2394 Improve magical zombie pills
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java
Labels: Hacktoberfest

#2404 Fixes #2403
  src/main/java/me/mrCookieSlime/Slimefun/api/inventory/DirtyChestMenu.java
Labels: Hacktoberfest

#2384 Added Elytra Cap
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/ProtectionType.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/ElytraCap.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ElytraCrashListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/resources/languages/researches_en.yml
Labels: Hacktoberfest, hacktoberfest-accepted

#2396 Add sticks recipe to table saw
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/TableSaw.java
Labels: Hacktoberfest, hacktoberfest-accepted

#1909 Addition: Bee Armor
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BeeWingListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunBootsListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/resources/languages/researches_en.yml
Labels: Merge Conflicts

#2407 Added some code-style guidelines to CONTRIBUTING
  CONTRIBUTING.md
Labels: Technical Thread

#2402 GPS Control Panel and GEO Scanner access checks
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOScanner.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/gps/GPSControlPanel.java
  src/main/resources/plugin.yml
Labels: Hacktoberfest

#2413 Zombie pill fix
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java
Labels: Hacktoberfest

#2440 Fixed #2439
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: Hacktoberfest, hacktoberfest-accepted

#2435 Stop unwanted actions from StrangeNetherGoo and Heavy Cream
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/HeavyCream.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: Hacktoberfest

#2451 Fix #2433
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GoldPan.java
Labels: Hacktoberfest

#2382 Energy Connectors
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/EnergyNetComponent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNetComponentType.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/CargoConnectorNode.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/EnergyConnector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/HeadTexture.java
  src/main/resources/languages/researches_en.yml
Labels: Hacktoberfest, hacktoberfest-accepted

#2456 Added Basalt + Blackstone to Crucible
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectrifiedCrucible.java
Labels: Hacktoberfest

#2467 Nether Goo "Tainted Sheep"
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java
Labels: Hacktoberfest

#2477 fixes #2470
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/tags/SlimefunTag.java
  src/main/resources/tags/block_placer_ignored_materials.json
  src/main/resources/tags/pressure_plates.json
  src/main/resources/tags/sensitive_materials.json
  src/main/resources/tags/tall_flowers.json
  src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/tags/TestSlimefunTags.java
Labels: Hacktoberfest

#2479 Fixes damage taken from Enderpearl with Enderboot on
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunBootsListener.java
Labels: Hacktoberfest

#2501 Changed some things to public (from protected)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/Instruction.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
Labels: Hacktoberfest

#2510 Fixes #2509
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
Labels: Hacktoberfest

#2473 Fixes ArmorForge
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/BackpackCrafter.java
Labels: Hacktoberfest
