Repository Slimefun/Slimefun4, pull requests merged in 2021-08, with the labels that each got.

#3179 Fix a flaky test
  src/test/java/io/github/thebusybiscuit/slimefun4/api/items/settings/TestMaterialTagSetting.java
Labels: ✨ Fix

#3186 Added sneaking check to ExplosiveTool
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
Labels: 🎈 Feature

#3059 Add Rainbow Armor
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/RainbowArmorPiece.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/AbstractArmorTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/ArmorTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/RainbowArmorTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
  src/main/resources/config.yml
  src/main/resources/languages/en/researches.yml
Labels: 🎈 Feature

#3131 Radiation update
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/Radioactivity.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/Medicine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/Vitamins.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/RadioactivityListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/ArmorTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/RadioactivityTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/RadiationSymptom.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/RadiationUtils.java
  src/main/resources/config.yml
  src/main/resources/languages/en/messages.yml
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TestArmorTask.java
Labels: ⏰ Waiting for response, 🎈 Feature

#3191 Use chest menu preset in GUI
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricSmeltery.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/reactors/Reactor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOMiner.java
Labels: 🧹 Chores

#3192 Add Enhanced furnaces' luck multiplier for raw ores in 1.17
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/EnhancedFurnaceListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/tags/SlimefunTag.java
  src/main/resources/tags/enhanced_furnace_luck_materials.json
  src/main/resources/tags/raw_metals.json
Labels: 🎈 Feature

#3204 Fix pickup delay not being set
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
Labels: ✨ Fix

#3200 Update message to show category
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
Labels: 🎈 Feature

#3196 WorldBorder Support
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/FarmerAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/MinerAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java
Labels: ✨ Fix
