Repository Slimefun/Slimefun4, pull requests merged in 2021-09, with the labels that each got.

#3226 Fixes #3225 and chunk data not being saved on shutdown
  src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
Labels: ✨ Fix

#3228 Fixes #3206
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
Labels: ✨ Fix

#3229 Fixed ender lump guide entry
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: ✨ Fix

#3237 Update repo
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/MetricsService.java
Labels: ✨ Fix

#3238 Fix metrics not being able to download
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/MetricsService.java
Labels: ✨ Fix

#3259 Fixes #3248
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
Labels: ✨ Fix

#3258 Improves item comparison performance
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ItemFilter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
Labels: 💡 Performance Optimization

#3253 Hercules' Pickaxe supports 1.17 deepslate ores and copper
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/HerculesPickaxe.java
Labels: ✨ Fix

#3274 Add missing recipes to Electrified Crucible
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectrifiedCrucible.java
Labels: 🎈 Feature

#3252 Smithing table listener
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/SmithingTableListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/package-info.java
  src/main/resources/languages/en/messages.yml
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSmithingTableListener.java
Labels: ✨ Fix

#3279 Fixes #3265
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java
Labels: ✨ Fix

#3292 Removed useless overriding
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/SolarGenerator.java
Labels: ✨ Fix
