Repository Slimefun/Slimefun4, pull requests merged in 2021-12, with the labels that each got.

#3315 Re-adding gravity_affected_blocks.json and adding "GRAVITY_AFFECTED_BLOC…
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/tags/SlimefunTag.java
  src/main/resources/tags/gravity_affected_blocks.json
Labels: 🔧 API

#3297 Update wiki.json
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/Jetpack.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/Talisman.java
  src/main/resources/wiki.json
Labels: 🧹 Chores

#3367 (API) Added Biome Maps [1.18 preparation]
  CHANGELOG.md
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/api/exceptions/BiomeMapException.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/AbstractResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/NetherIceResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/OilResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/SaltResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/UraniumResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/PatternUtils.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeDataConverter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMap.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMapParser.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/package-info.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/tags/TagParser.java
  src/main/resources/biome-maps/nether_ice_v1.14.json
  src/main/resources/biome-maps/nether_ice_v1.16.json
  src/main/resources/biome-maps/oil_v1.14.json
  src/main/resources/biome-maps/salt_v1.14.json
  src/main/resources/biome-maps/uranium_v1.14.json
  src/main/resources/biome-maps/uranium_v1.16.json
  src/main/resources/biome-maps/uranium_v1.17.json
  src/test/java/io/github/thebusybiscuit/slimefun4/api/geo/TestResourceRegistration.java
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/biomes/TestBiomeMap.java
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/biomes/TestBiomeMapCompatibility.java
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/biomes/TestBiomeMapParser.java
  src/test/resources/biomes/1.14.x.json
  src/test/resources/biomes/1.15.x.json
  src/test/resources/biomes/1.16.x.json
  src/test/resources/biomes/1.17.x.json
  src/test/resources/biomes/1.18.x.json
Labels: 🔧 API

#3369 Added 1.18 support
  .github/workflows/discord-webhook.yml
  .github/workflows/maven-compiler.yml
  .github/workflows/sonarcloud.yml
  CHANGELOG.md
  README.md
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/geo/ResourceManager.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/GPSNetwork.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/OilResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/SaltResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/UraniumResource.java
  src/main/resources/biome-maps/oil_v1.18.json
  src/main/resources/biome-maps/salt_v1.18.json
  src/main/resources/biome-maps/uranium_v1.18.json
  src/test/java/io/github/thebusybiscuit/slimefun4/api/geo/TestResourceRegistration.java
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/biomes/TestBiomeMapCompatibility.java
Labels: 🤝 Compatibility

#3377 Improved the API for BiomeMap
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/AbstractResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMap.java
Labels: 🔧 API

#3381 make parachute class respect constructor recipetype parameter
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/Parachute.java
Labels: 🧹 Chores

#3305 Added Talisman of the Farmer (approved suggestion)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/tags/SlimefunTag.java
  src/main/resources/languages/en/messages.yml
  src/main/resources/languages/en/researches.yml
  src/main/resources/tags/farmer_talisman_triggers.json
Labels: 🎈 Feature

#3387 Fixes #3385
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
Labels: ✨ Fix

#3392 fix easter apple pie recipe output
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: ✨ Fix
