Repository Slimefun/Slimefun4, pull requests merged in 2021-05, with the labels that each got.

#3006 Add a new header pointing to existing issues and Discord
  .github/ISSUE_TEMPLATE/bug-report-beta.yaml
Labels: 🔧 Technical Thread

#3016 Fixed a typo
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/PostSetup.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java
  src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/TestSlimefunItem.java
Labels: 🧹 Chores

#3032 Add grinding of higher level lumps back into 4 lower level lumps
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
Labels: 🎈 Feature

#3031 Update Pickaxe of The Seeker Localization
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/PickaxeOfTheSeeker.java
  src/main/resources/languages/en/messages.yml
Labels: ✨ Fix

#3033 Fixes #2978
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java
Labels: ✨ Fix

#3003 Potentially fixed #2927
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/holograms/HologramsService.java
Labels: ✨ Fix

#3015 Improved memory usage of cargo/energy networks and fixed #3013
  CHANGELOG.md
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/api/network/Network.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/NetworkManager.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/NetworkListener.java
Labels: ✨ Fix, 💡 Performance Optimization

#3038 Fixed explosive tool handling for blocks with a BlockBreakHandler
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
Labels: ✨ Fix

#2983 Add the option to disable learning animations server & client side
  src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/SlimefunGuideImplementation.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/LearningAnimationOption.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/SlimefunGuideSettings.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/ContributionsConnector.java
  src/main/resources/config.yml
  src/main/resources/languages/en/messages.yml
Labels: 🎈 Feature

#3051 test
  .github/workflows/auto-approve.yml
  .github/workflows/auto-squash.yml
Labels: ✨ Fix

#3061 Fix Icy Bow ignores shields
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/ExplosiveBow.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/IcyBow.java
Labels: ✨ Fix

#3044 Add PortableTeleporter
  src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/TeleportationManager.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/teleporter/PortableTeleporter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TeleporterListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/resources/languages/en/researches.yml
Labels: 🎈 Feature

#3065 Fixed an Exception when any GoldPan drops have zero chance of dropping
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GoldPan.java
Labels: ✨ Fix

#3058 Fixed menu loading issues and probably improved BlockStorage load times
  src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
Labels: ✨ Fix

#3052 Fix WoodcutterAndroid getting stuck while chopping a tree with full inventory
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java
  src/main/java/me/mrCookieSlime/Slimefun/api/inventory/DirtyChestMenu.java
Labels: ✨ Fix

#3062 Add a configurable step delay to the Ancient Altar
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientAltar.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/AncientAltarTask.java
Labels: 🎈 Feature

#3068 Optimized use of ItemStackWrapper in the CargoNetworkTask
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/AbstractItemNetwork.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ItemFilter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ItemStackAndInteger.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/itemstack/ItemStackWrapper.java
  src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/utils/TestItemStackWrapper.java
Labels: 💡 Performance Optimization

#3080 Easier SlimefunItem creation with small recipe
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java
Labels: 🔧 API

#2779 Rewrote Machine Processing API
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AsyncGeneratorProcessCompleteEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AsyncMachineOperationFinishEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AsyncMachineProcessCompleteEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AsyncReactorProcessCompleteEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/MachineProcessHolder.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/machines/MachineOperation.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/machines/MachineProcessor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/machines/package-info.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/reactors/Reactor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOMiner.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/operations/CraftingOperation.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/operations/FuelOperation.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/operations/MiningOperation.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/operations/package-info.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java
Labels: 🔧 API

#3083 added time and date to error report
  src/main/java/io/github/thebusybiscuit/slimefun4/api/ErrorReport.java
Labels: 🧹 Chores

#3092 Fix IllegalArgumentException when ChestTerminal is requesting items
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java
Labels: ✨ Fix

#3096 AutoBrewer fixes
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoBrewer.java
Labels: ✨ Fix
