Repository Slimefun/Slimefun4, pull requests merged in 2021-07, with the labels that each got.

#3043 Change the way the TickerTask tracks Blocks
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TestTickerCollection.java
Labels: 💡 Performance Optimization

#3146 Minor changes to the ticker task
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerThreadFactory.java
Labels: 🧹 Chores

#3142 Fix Vanilla Auto Crafter Being Able to Craft Disabled Items
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AutoCrafterListener.java
  src/main/resources/languages/en/messages.yml
Labels: ✨ Fix

#3145 Allow IndustrialMiner to mine when minWorldHeight is lower than 0
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java
Labels: ✨ Fix

#3151 Add Amethyst Block -> 4 Amethyst Shard recipe to grindstone
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
Labels: 🎈 Feature

#3163 Add the option to prevent IndustrialMiner from mining deepslate ores
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java
Labels: 🎈 Feature

#3169 Allow the Industrial Miner to produce raw ores rather than ore blocks
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java
Labels: 🎈 Feature

#3168 Adds deepslate iron, gold, copper ores, and copper ore to Ore Crusher
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
Labels: 🎈 Feature

#3117 Add LimitedUseItem - base class for items with limited uses
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/LimitedUseItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/StormStaff.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/LoreBuilder.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/PatternUtils.java
Labels: 🔧 API

#3171 Fixes Talisman of anvil break main hand item in special case
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
Labels: ✨ Fix

#3138 Fix disappearing items with output chest by machines
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/ItemSpawnReason.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/PressureChamber.java
Labels: ✨ Fix

#3167 Fix renamed items turning into valid-ish items for crafting purposes
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java
Labels: ✨ Fix

#3181 Update wiki.json
  src/main/resources/wiki.json
Labels: 🧹 Chores

#3134 Intregation: Orebfuscator
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/integrations/IntegrationsManager.java
  src/main/java/io/github/thebusybiscuit/slimefun4/integrations/OrebfuscatorIntegration.java
  src/main/resources/plugin.yml
Labels: 🤝 Compatibility

#3109 Fixes #2677
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
Labels: ✨ Fix

#3107 FlexCategories can now be made visible in CheatSheet and Survival SlimefunGuide
  src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/FlexCategory.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/MultiCategory.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
Labels: 🧹 Chores
