Repository Slimefun/Slimefun4, pull requests merged in 2021-01, with the labels that each got.

#2698 Inventory selector for elevators
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AndroidFarmEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/PlayerPreResearchEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/ItemSetting.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/RechargeableHelper.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/LockedCategory.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/OpenGuideCommand.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/SlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/SlimefunGuideImplementation.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/SlimefunGuideLayout.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/GuideLayoutOption.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNet.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/AutoSavingService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/BackupService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/BlockDataService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/CustomItemDataService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/LocalizationService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/ContributionsConnector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/Contributor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubConnector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubIssuesConnector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/plugins/ThirdPartyPluginService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SlimefunProfiler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/BookSlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/ChestSlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/AdvancedFarmerAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/FarmerAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/Instruction.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/Script.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/gps/ElevatorPlate.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/MagicianTalisman.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/ActiveMiner.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/DebugFishListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunGuideListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/WorldListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/PostSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/SlimefunStartupTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/integrations/IntegrationsManager.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
  src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
  src/main/java/me/mrCookieSlime/Slimefun/api/Slimefun.java
  src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenu.java
  src/main/resources/config.yml
  src/main/resources/languages/messages_hu.yml
  src/main/resources/languages/messages_zh-TW.yml
  src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/guide/TestBookSlimefunGuide.java
Labels: ⚡ Merge Conflicts

#2487 Furnace based machines could no longer be used as vanilla furnace with the hoppers.
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/NotHopperable.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoBrewer.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoDrier.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricFurnace.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricIngotPulverizer.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricOreGrinder.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricSmeltery.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/HopperListener.java
Labels: Hacktoberfest

#2645 Experimental talismans
  .gitignore
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/ResurrectedTalisman.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/Talisman.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/resources/languages/messages_en.yml
  src/main/resources/languages/researches_en.yml
Labels: ⏰ Waiting for response

#2755 Check inv maxStackSize
  src/main/java/me/mrCookieSlime/Slimefun/api/inventory/DirtyChestMenu.java
Labels: ✨ Fix

#2765 Fix #2761 probably
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricSmeltery.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/HeatedPressureChamber.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
Labels: ✨ Fix

#2627 Added PR labels
  .github/workflows/pr-labels.yml
Labels: ⏰ Waiting for response, 🧹 Chores

#2599 Add Tier 3 Electric Ore Grinder
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: 🎈 Feature

#2481 Fix issue #2460 Explosive tools not working with silk touch
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
Labels: Hacktoberfest, hacktoberfest-accepted, ⏰ Waiting for response, ✨ Fix

#2757 Fix #2679
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/MagicianTalisman.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
Labels: ✨ Fix
