Repository Slimefun/Slimefun4, pull requests merged in 2021-02, with the labels that each got.

#2782 Allow Talismans to use the Actionbar
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/SlimefunLocalization.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/Talisman.java
  src/main/resources/config.yml
Labels: 🎈 Feature

#2643 Refactoring for hasUnlocked() checks
  src/main/java/io/github/thebusybiscuit/slimefun4/api/network/Network.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/LockedCategory.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/SlimefunLocalization.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/EnchantmentRune.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/SoulboundRune.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/Talisman.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AbstractSmeltery.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BeeWingsListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/CoolerListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ElytraImpactListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/GadgetsListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunBootsListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunItemConsumeListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunItemInteractListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VampireBladeListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/entity/EntityInteractionListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/entity/MobDropListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/ArmorTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java
  src/main/java/me/mrCookieSlime/Slimefun/api/Slimefun.java
Labels: 🧹 Chores

#2791 Add java ver and hover to versions subcommand
  src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java
Labels: 🎈 Feature

#2801 Updated czech translations
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/Translators.java
  src/main/resources/languages/categories_cs.yml
  src/main/resources/languages/recipes_cs.yml
  src/main/resources/languages/researches_cs.yml
Labels: 📄 Translations Update

#2597 Refactoring + Fixes to Block Handlers
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/handlers/BlockBreakHandler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/handlers/BlockPlaceHandler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/handlers/SimpleBlockBreakHandler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/handlers/package-info.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/HologramProjector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/AbstractFilterNode.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/CargoManager.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/ReactorAccessPort.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/EnergyRegulator.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/reactors/Reactor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOMiner.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/gps/GPSTransmitter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MiningAndroidListener.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunBlockHandler.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/UnregisterReason.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/interfaces/InventoryBlock.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/handlers/ItemHandler.java
  src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
Labels: ✨ Fix

#2830 Fix duplicating woods when unable to replant
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java
Labels: ✨ Fix
