Repository Slimefun/Slimefun4, pull requests merged in 2021-06, with the labels that each got.

#3097 Change config for consistency and improvement
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem.java
  src/main/resources/config.yml
Labels: 🧹 Chores

#3098 Add charcoal -> coal recipe
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
Labels: 🎈 Feature

#3077 Added WeaponUseHandler
  src/main/java/io/github/thebusybiscuit/slimefun4/core/handlers/WeaponUseHandler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/VampireBlade.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunItemHitListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VampireBladeListener.java
Labels: 🔧 API

#3102 Add collectAverageTimings to SlimefunProfiler
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SlimefunProfiler.java
Labels: 🔧 API

#3106 Hidden items are now not shown in the SlimefunGuide when using search
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
Labels: ✨ Fix

#3121 1.17 exists now
  .github/ISSUE_TEMPLATE/bug-report-beta.yaml
Labels: ✨ Fix

#3127 Add a freeze effect on the Icy Bow (1.17)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/IcyBow.java
Labels: 🎈 Feature

#3126 Encourage Java 16 on older versions
  src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/entities/ProduceCollector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java
Labels: 🧹 Chores

#3118 Add diamond -> coal conversion
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
Labels: 🎈 Feature

#3119 Add Trident recipe
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/resources/languages/en/researches.yml
Labels: 🎈 Feature
