Repository Slimefun/Slimefun4, pull requests merged in 2021-03, with the labels that each got.

#2827 Fix multiple Book Binder issues.
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java
Labels: ✨ Fix

#2328 Programmable Android Optimization: Infinite Block Generators
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/MinerAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/InfiniteBlockGenerator.java
  src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/utils/TestInfiniteBlockGenerators.java
Labels: 💡 Performance Optimization

#2681 Multi-Category support
  src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/MultiCategory.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/SubCategory.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/Category.java
Labels: 🔧 API

#2859 Added ExplosiveToolBreakBlockEvent
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlocksEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
Labels: 🔧 API

#2885 Switch the last two items in Magical Items
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: 🧹 Chores

#2866 Fix addon blockmenu loading with custom worlds
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/SlimefunStartupTask.java
Labels: ✨ Fix

#2888 Allow onBlockBreak to be cancelled by BlockBreakHandler
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: ✨ Fix

#2756 Enchant level limit
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
  src/main/resources/languages/messages_en.yml
Labels: 🎈 Feature

#2807 Added Vanilla Auto-Crafter and Enhanced Auto-Crafter
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/AbstractAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/AbstractRecipe.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/EnhancedAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/SlimefunAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/SlimefunItemRecipe.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/VanillaAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/VanillaRecipe.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/package-info.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/entities/XPCollector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/AsyncRecipeChoiceTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/HeadTexture.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
  src/main/resources/languages/messages_en.yml
  src/main/resources/languages/researches_en.yml
  src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/auto_crafters/TestAbstractRecipe.java
  src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/auto_crafters/TestAutoCrafter.java
Labels: 🎈 Feature

#2898 Follow up PR on AutoCrafters
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/AbstractAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/SlimefunAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/SlimefunItemRecipe.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/VanillaAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/VanillaRecipe.java
Labels: 🧹 Chores

#2900 Fixed a Message
  src/main/resources/plugin.yml
Labels: 🧹 Chores

#2915 Fixes #2914
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOMiner.java
Labels: ✨ Fix

#2917 The update that fixed world hunger (or how I made a cake factory)
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/AsyncMachineProcessCompleteEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/autocrafters/AbstractAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/BlockPlacer.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoDrier.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/CarbonPress.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/entities/AnimalProduce.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/entities/ProduceCollector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AutoCrafterListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
  src/main/resources/languages/researches_en.yml
Labels: 🎈 Feature

#2907 Added 2 missing researches
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/resources/languages/researches_en.yml
Labels: ✨ Fix

#2916 Fixed 2650
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SoulboundListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
  src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestSoulboundListener.java
Labels: ✨ Fix

#2924 Added a new message to multiblocks to see if inventory is empty
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java
  src/main/resources/languages/messages_en.yml
Labels: 🎈 Feature

#2919 Fixed damageable items not respecting `unbreakable` tag
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java
Labels: ✨ Fix
