Repository Slimefun/Slimefun4, pull requests merged in 2021-04, with the labels that each got.

#2950 Optimizations to cargo
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNet.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java
Labels: 💡 Performance Optimization

#2956 Fixes #2942
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/LocalizationService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/Language.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/SlimefunLocalization.java
Labels: ✨ Fix

#2965 Add Quartz Block -> 4 Quartz to Grind Stone (Suggestion-746)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
Labels: 🎈 Feature

#2970 Protected
  src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/FlexCategory.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/handlers/BlockBreakHandler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/handlers/BlockPlaceHandler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/handlers/SimpleBlockBreakHandler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/SimpleSlimefunItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/AbstractFilterNode.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutomatedCraftingChamber.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/accelerators/AbstractGrowthAccelerator.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/accelerators/CropGrowthAccelerator.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/reactors/NetherStarReactor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/reactors/NuclearReactor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/reactors/Reactor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/gps/GPSTransmitter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/MedicalSupply.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AbstractSmeltery.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/SlimefunBow.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java
  src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenuPreset.java
Labels: 🧹 Chores

#2963 Add Block of Coal -> Carbon recipe to the Carbon Press and Compressor
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/CarbonPress.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
Labels: 🎈 Feature

#2967 Add tier II machines to Auto Enchanter and Auto Disenchanter (Suggestion 311)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/resources/languages/researches_en.yml
Labels: 🎈 Feature

#2988 Fixes NPE when hand is empty while talisman of the anvil triggers
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
Labels: ✨ Fix

#2982 Fixes #2977
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
Labels: ✨ Fix

#2911 Check lore to determine whether (Dis)Enchantable
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/ItemSetting.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AbstractEnchantmentMachine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
Labels: 🎈 Feature

#2290 Performance improvements on TickerTask <Tested>
  CHANGELOG.md
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/ProfilerThreadFactory.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SlimefunProfiler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerThreadFactory.java
Labels: 💡 Performance Optimization

#2993 Main Menu Page History Fix
  src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/GuideHistory.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
Labels: ✨ Fix

#2994 Fix android click handler errors while moving
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
Labels: ✨ Fix

#3002 New form-based Issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: 🔧 Technical Thread
