Repository Slimefun/Slimefun4, pull requests merged in 2022-04, with the labels that each got.

#3541 Fix Arithmetic Error
  src/main/java/io/github/thebusybiscuit/slimefun4/core/machines/MachineProcessor.java
Labels: ✨ Fix

#3546 Added Seagrass recipe (suggestion #398 from Mr.Moules)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FoodComposter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FoodFabricator.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: 🎈 Feature

#3427 Removed ChestTerminal support
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/AbstractItemNetwork.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNet.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ItemRequest.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/cargo/AbstractCargoNode.java
  src/main/java/io/github/thebusybiscuit/slimefun4/integrations/IntegrationsManager.java
Labels: 🧹 Chores
