Repository Slimefun/Slimefun4, pull requests merged in 2022-09, with the labels that each got.

#3652 "Fixing" Dust Order
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: 🧹 Chores

#3500 added freezer 3
  src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlock.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: 🎈 Feature

#3363 Register filled flask as a Slimefun Item
  src/main/java/io/github/thebusybiscuit/slimefun4/api/recipes/RecipeType.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/HiddenItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: 🧹 Chores

#3594 Added Glow Berries Being Useful
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/resources/wiki.json
Labels: ⏰ Waiting for response, 🎈 Feature
