Repository Slimefun/Slimefun4, pull requests merged in 2022-07, with the labels that each got.

#3564 Add ensure compatibility in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🧹 Chores

#3598 Fixes mud not working with explosive shovel
  src/main/resources/tags/dirt_variants.json
Labels: ✨ Fix

#3492 added tinted glass
  src/main/resources/tags/glass_blocks.json
Labels: 🧹 Chores

#3607 added wool tag
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/tags/SlimefunTag.java
  src/main/resources/tags/block_placer_ignored_materials.json
  src/main/resources/tags/wool_carpets.json
Labels: 🎈 Feature

#3503 Fix bee wings erroring on startup
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BeeWingsListener.java
Labels: ✨ Fix

#3473 Improve Round-Robin Accuracy
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java
Labels: 🧹 Chores

#3608 Allow addons to disable warning
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/ItemGroup.java
Labels: 🔧 API

#3277 Allow admins to control the behavior of the Electric Gold Pan via the…
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricGoldPan.java
Labels: 🎈 Feature

#3555 chore: Set permissions for GitHub actions
  .github/workflows/auto-approve.yml
  .github/workflows/json-validator.yml
  .github/workflows/maven-compiler.yml
  .github/workflows/sonarcloud.yml
Labels: 🧹 Chores

#3620 added a way to turn mud into clay
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoDrier.java
Labels: 🎈 Feature
