Repository Slimefun/Slimefun4, pull requests merged in 2022-01, with the labels that each got.

#3401 Add fuel types to BioGenerator
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/BioGenerator.java
Labels: 🎈 Feature

#3425 Ability to use isLenient flag of BiomeMapParser
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMap.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMapParser.java
Labels: 🔧 API

#3428 Added vanilla ratios to the freezer
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/Freezer.java
Labels: 🎈 Feature

#3431 Update dough
  CHANGELOG.md
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/integrations/IntegrationsManager.java
Labels: 🧹 Chores

#3275 Fixes #3133
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
Labels: ✨ Fix
