Repository Slimefun/Slimefun4, pull requests merged in 2022-03, with the labels that each got.

#3477 unlocalized name and some docs
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/researches/Research.java
Labels: 🧹 Chores, 👍 Approved but postponed (post DEV-1000)

#3309 Implement Middle Click support for Slimefun Items
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MiddleClickListener.java
Labels: 🎈 Feature, 👍 Approved but postponed (post DEV-1000)

#3448 Improve guide search result
  src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
  src/main/resources/config.yml
Labels: 🧹 Chores

#3451 Allow Fluid Pump to fill water bottles
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java
Labels: 🎈 Feature

#3485 fixes #3483
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MiddleClickListener.java
Labels: ✨ Fix

#3470 added rooted dirt to dirt variants
  src/main/resources/tags/dirt_variants.json
Labels: ✨ Fix

#3479 Fix pedestal item disappearing
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java
Labels: ✨ Fix

#3453 Industrial miner unintentional fuel consuming fix
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java
Labels: ✨ Fix

#3491 Add shulker box to ColoredMaterial
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/ColoredMaterial.java
Labels: 🧹 Chores

#3496 Add candle to ColoredMaterial
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/ColoredMaterial.java
Labels: 🧹 Chores
