Repository Slimefun/Slimefun4, pull requests merged in 2023-11, with the labels that each got.

#3928 Add MultiBlockCraftEvent (Updated version of #3439)
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/MultiBlockCraftEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AbstractSmeltery.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AutomatedPanningMachine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Juicer.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreWasher.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/PressureChamber.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/TableSaw.java
Labels: 🔧 API, Build tested

#3760 fix taking damage on head collision while wearing elytra cap
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ElytraImpactListener.java
Labels: ✨ Fix, Build tested

#3969 Remove Lore Check from Slimefun Guide
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunGuideListener.java
Labels: 🧹 Chores

#3925 don't consume bookbinder inputs if the output is worse than the input
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/BookBinder.java
Labels: ✨ Fix, Build tested

#4027 fix heads showing as steve
  pom.xml
Labels: ✨ Fix

#3884 E2E testing
  .github/workflows/e2e-testing.yml
  .github/workflows/pull-request.yml
Labels: 🎈 Feature

#3911 Deny placement when deletion is queued
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
  src/main/resources/languages/en/messages.yml
  src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunBlockBreakEvent.java
  src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunBlockPlaceEvent.java
  src/test/java/io/github/thebusybiscuit/slimefun4/test/TestUtilities.java
Labels: ✨ Fix, Build tested
