Repository Slimefun/Slimefun4, pull requests merged in 2023-01, with the labels that each got.

#3706 Fix #3705
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/groups/NestedItemGroup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/groups/SubItemGroup.java
Labels: ✨ Fix

#3737 Update changelog (Worse than Walshy's version)
  .github/workflows/maven-compiler.yml
  CHANGELOG.md
Labels: 🧹 Chores

#3739 RC 34 is next up
  CHANGELOG.md
Labels: 🧹 Chores

#3646 Drop support for 1.14, 1.15
  src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/recipes/RecipeType.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlock.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/autocrafters/AbstractAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/BioGenerator.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricPress.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectrifiedCrucible.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/entities/IronGolemAssembler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/elevator/ElevatorPlate.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/OreDictionary.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/OreDictionary14.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/OreDictionary16.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ClimbingPick.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/SeismicAxe.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/NetherIceResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/OilResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/SaltResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/resources/UraniumResource.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/WorldUtils.java
  src/main/resources/biome-maps/nether_ice_v1.14.json
  src/main/resources/biome-maps/oil_v1.16.json
  src/main/resources/biome-maps/salt_v1.16.json
  src/main/resources/biome-maps/uranium_v1.14.json
  src/main/resources/plugin.yml
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestMinecraftVersion.java
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/biomes/TestBiomeMapCompatibility.java
Labels: 🎮 Game Update, ⏰ Scheduled

#3751 remove 1.14 from comments and others
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java
Labels: 🧹 Chores

#3746 more use for cobbled deepslate
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
Labels: 🎈 Feature

#3756 Fix smelting null items
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/EnhancedFurnaceListener.java
Labels: ✨ Fix

#3695 Some cleanup
  src/main/java/io/github/thebusybiscuit/slimefun4/core/handlers/RainbowTickHandler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/BlockDataService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/autocrafters/AbstractAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/tags/SlimefunTag.java
  src/main/resources/tags/auto_crafter_supported_storage_blocks.json
  src/main/resources/tags/cargo_supported_storage_blocks.json
  src/main/resources/tags/tile_entities.json
Labels: hacktoberfest-accepted, 🧹 Chores
