Repository Slimefun/Slimefun4, pull requests merged in 2023-06, with the labels that each got.

#3828 Fix android move task
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
Labels: ✨ Fix

#3639 Fix industrial miner mining up sf blocks
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java
Labels: ✨ Fix

#3640 Higher level interact event cancellation to prevent flask of knowledge from able to fill up water
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/KnowledgeFlask.java
Labels: ✨ Fix

#3659 Update soulbound rune to respect itemPickupDelay()
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/SoulboundRune.java
Labels: ✨ Fix

#3794 Make Fire Staff not disenchantable by default
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/EnchantedItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: ✨ Fix

#3686 adds a way to automate salt
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreWasher.java
Labels: hacktoberfest-accepted, 🎈 Feature

#3697 withers shouldnt cause ghost bs anymore
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java
Labels: ✨ Fix

#3749 added a way to set max enchants to go on an item
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AbstractEnchantmentMachine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
Labels: 🎈 Feature

#3681 Check if player is crouching
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/LumberAxe.java
Labels: hacktoberfest-accepted, 🎈 Feature

#3839 1.20
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/biomes/TestBiomeMapCompatibility.java
  src/test/resources/biomes/1.20.x.json
Labels: 🎮 Game Update

#3847 Change typo and logic issues with Enchant Amount problems
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AbstractEnchantmentMachine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
Labels: ✨ Fix

#3595 added block events
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/SlimefunBlockBreakEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/SlimefunBlockPlaceEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
  src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
  src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunBlockBreakEvent.java
  src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunBlockPlaceEvent.java
Labels: 🔧 API

#3862 Fix incorrect return in BlockListener
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: ✨ Fix

#3798 Add new methods in BlockStorage and TickerTask for clearing all block info in a chunk
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
  src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
Labels: 🔧 API

#3865 Rename amarcais53 to HamtaBot
  src/main/resources/languages/translators.json
Labels: ✨ Fix

#3870 Download artifact by ID, it isn't available in the workflow_run
  .github/workflows/preview-builds.yml
Labels: 🧹 Chores

#2844 [CI Skip] Allow server owners to fully customize sounds
  src/main/java/io/github/thebusybiscuit/slimefun4/api/researches/PlayerResearchTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundConfiguration.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundEffect.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/package-info.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/FishermanAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/LongFallBoots.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/backpacks/EnderBackpack.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/entities/IronGolemAssembler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/DietCookie.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/MagicSugar.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/InfusedHopper.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/KnowledgeFlask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/KnowledgeTome.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicEyeOfEnder.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/SoulboundRune.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/VillagerRune.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/WindStaff.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/Splint.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/Vitamins.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AbstractSmeltery.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AutomatedPanningMachine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Juicer.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/PressureChamber.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/LumberAxe.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/PortableCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/PortableDustbin.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/ExplosiveBow.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/VampireBlade.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ElytraImpactListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunBootsListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/InfusedMagnetTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/JetBootsTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/JetpackTask.java
Labels: 🎈 Feature

#3882 Revert header changes
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/PermissionsService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundService.java
Labels: ✨ Fix

#3883 Fixed 1.16 compat
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundService.java
Labels: ✨ Fix

#3795 Fix Disabled Items Shifting Multiblock Recipes
  src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java
Labels: ✨ Fix
