Repository Slimefun/Slimefun4, pull requests merged in 2023-08, with the labels that each got.

#3912 Add blackstone recipes to Grindstone and Ore Crusher
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
Labels: 🎈 Feature

#3591 Add Enchanted Golden Apple recipe (suggestion #2147 from punished_Garett)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
Labels: 🎈 Feature

#3932 Fix Soulbound Runes not working
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/SoulboundRune.java
Labels: ✨ Fix

#3246 Added new flags for timings
  src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/TimingsCommand.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/PerformanceInspector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/PerformanceSummary.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SummaryOrderType.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/inspectors/ConsolePerformanceInspector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/inspectors/PlayerPerformanceInspector.java
Labels: 🎈 Feature, Build tested

#3914 Add cherry log to android woodcutter (Fixes #3913)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java
Labels: ✨ Fix

#3944 change BREAK_BLOCK to PLACE_BLOCK in BlockPlaceEvent
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: 🎯 Needs testing, ✨ Fix

#3941 Fix unable to craft soulbound backpack with woven backpack with id
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java
Labels: ✨ Fix

#3924 correctly handle sensitive blocks above blocks broken with explosive tool
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: ✨ Fix

#3946 Enforce LF endings automatically
  .gitattributes
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/SlimefunGuideOpenEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/RandomMobDrop.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/handlers/RainbowTickHandler.java
Labels: 🧹 Chores
