Repository Slimefun/Slimefun4, pull requests merged in 2023-09, with the labels that each got.

#3962 Add SlimefunItem#getOptionalByX
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java
Labels: 🔧 API

#3951 fix getting radiated when not supposed to
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/JoinListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/armor/RadiationTask.java
Labels: 🎯 Needs testing, ✨ Fix

#3940 Fixes duplication glitch with explosive tools in combination with itemsadder
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
  src/main/java/io/github/thebusybiscuit/slimefun4/integrations/IntegrationsManager.java
Labels: ✨ Fix, Build tested

#3973 fix generating geo resources every scan
  src/main/java/io/github/thebusybiscuit/slimefun4/api/geo/ResourceManager.java
Labels: ✨ Fix

#3976 fix breaking sf block with not unlocked item duping contents
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: ✨ Fix

#3970 capitalized Chosen
  src/main/resources/config.yml
Labels: 🧹 Chores
