Repository Slimefun/Slimefun4, pull requests merged in 2023-03, with the labels that each got.

#3787 Fix #3462
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
Labels: ✨ Fix

#3752 Added bamboo as a fuel type for androids
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
Labels: 🎈 Feature

#3779 Fix #3724
  src/main/resources/tags/mangrove_base_blocks.json
Labels: ✨ Fix

#3783 Fix Energy Nets Over&Underflowing
  src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestNumberUtils.java
Labels: ✨ Fix

#3707 Fix #3701
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/Juice.java
Labels: ✨ Fix

#3679 Add Basalt->Blackstone recipe
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
Labels: hacktoberfest-accepted, 🎈 Feature

#3786 Fix #3361
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
Labels: ✨ Fix
