Repository Slimefun/Slimefun4, pull requests merged in 2023-12, with the labels that each got.

#4028 replace builds page with blob builds
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/UpdaterService.java
  src/test/java/io/github/thebusybiscuit/slimefun4/core/services/TestUpdaterService.java
Labels: 🧹 Chores

#3988 Add config option for radiation
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/resources/config.yml
Labels: hacktoberfest-accepted, 🎈 Feature

#3996 Filter unlocked researches of player
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/researches/Research.java
Labels: ✨ Fix

#3961 Allow sword of beheading drop piglin heads
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/SwordOfBeheading.java
Labels: 🎈 Feature, Build tested

#3990 Add compatibility for the 1.20 smithing table
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/SmithingTableListener.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSmithingTableListener.java
Labels: ✨ Fix

#4007 Update ButcherAndroidListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ButcherAndroidListener.java
Labels: ✨ Fix

#3919 skip already substituted parts when formatting message
  src/main/java/io/github/thebusybiscuit/slimefun4/core/debug/Debug.java
Labels: ✨ Fix

#4042 fix rate limiting issues
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubTask.java
Labels: ✨ Fix

#3966 Fix sensitive blocks attached to sf blocks not dropping (1.19+)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: ✨ Fix, Build tested

#4044 Strip colors from search term
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
  src/test/java/io/github/thebusybiscuit/slimefun4/core/guide/TestGuideOpening.java
Labels: ✨ Fix

#4048 Hotfix for the Sensistive Block Check
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: ✨ Fix

#4039 touch grass
  src/main/resources/tags/block_placer_ignored_materials.json
Labels: 🎯 Needs testing, 🎮 Game Update

#4050 Fixed vanilla sensitive blocks
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: ✨ Fix, Build tested

#4045 Add TalismanActivateEvent (Updated version of #3920)
  src/main/java/io/github/thebusybiscuit/slimefun4/api/events/TalismanActivateEvent.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/Talisman.java
  src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
Labels: 🔧 API, Build tested

#4066 Update changelog for RC-36
  CHANGELOG.md
Labels: 🧹 Chores

#4072 Fix contributor head being pullable
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubTask.java
Labels: ✨ Fix

#3934 Feature/block drop creative
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
  src/main/resources/config.yml
Labels: 🎈 Feature, Build tested
