Repository Slimefun/Slimefun4, pull requests merged in 2023-07, with the labels that each got.

#3417 DistinctiveItem/isSimilar + Backpack canStack
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DistinctiveItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/backpacks/SlimefunBackpack.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
Labels: ✨ Fix, Build tested

#3888 Fix breaking change in LongFallBoots
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/LongFallBoots.java
Labels: ✨ Fix

#3887 Fix Compressor doubling output
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
Labels: ✨ Fix

#3894 Cleanup and add version to preview builds
  .github/workflows/maven-compiler.yml
  .github/workflows/preview-builds.yml
  .github/workflows/pull-request.yml
Labels: 🧹 Chores

#3895 test
  .github/workflows/preview-builds.yml
Labels: 🧹 Chores

#3788 Adding ExternallyInteractable
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/ExternallyInteractable.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/interactions/InteractionResult.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/interactions/ItemInteractionResult.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/interactions/package-info.java
Labels: 🔧 API

#3890 Prepped for RC-35
  CHANGELOG.md
  README.md
Labels: 🧹 Chores

#3892 Cumulative Armor-Scheduling changes (Rainbow Armor + Radiation update)
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/HashedArmorpiece.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/RadiationSymptom.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/Radioactivity.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/Parachute.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/RainbowArmorPiece.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/JetBoots.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/Jetpack.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/SolarHelmet.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/BeeWings.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/Medicine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/Vitamins.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BeeWingsListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/GadgetsListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/RadioactivityListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/armor/AbstractArmorTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/armor/RadiationTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/armor/RainbowArmorTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/armor/SlimefunArmorTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/armor/SolarHelmetTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/player/AbstractPlayerTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/player/BeeWingsTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/player/InfusedMagnetTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/player/JetBootsTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/player/JetpackTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/player/ParachuteTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/LoreBuilder.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/RadiationUtils.java
  src/main/resources/config.yml
  src/main/resources/languages/en/messages.yml
  src/main/resources/languages/en/researches.yml
Labels: 🎈 Feature, Build tested

#3897 possibly fix javadocs
  src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java
Labels: ✨ Fix

#3896 Removed backwards compatiblity mode
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/ArmorTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/armor/SolarHelmetTask.java
  src/main/resources/config.yml
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/items/TestSlimefunItem.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestCargoNodeListener.java
Labels: 🧹 Chores

#3848 Fix some of the reported blocks not working
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AutoCrafterListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/DispenserListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/EnhancedFurnaceListener.java
  src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
Labels: ✨ Fix

#3899 Stop errors on forks
  .github/workflows/merge-conflicts.yml
Labels: 🧹 Chores

#3905 Improve performance of clearAllBlockInfoAtChunk, don't get immutable map
  src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java
Labels: 🧹 Chores

#3864 Fix possible custom enchantment duplication
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java
Labels: ✨ Fix

#3784 Ancient Pedestal Fixes
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/HologramProjector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java
Labels: ✨ Fix, Build tested

#3893 Gold Pan Rework (Continuation of #3269)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricGoldPan.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/AutomatedPanningMachine.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GoldPan.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/NetherGoldPan.java
Labels: 🎈 Feature, Build tested

#3923 Patch for #3922
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java
Labels: ✨ Fix, Build tested

#3926 fixed grappling hook not working due to bat dying
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GrapplingHook.java
Labels: ✨ Fix

#3654 - Adjust ticker times to show correct time on config changes for custom-ticker-delay
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/operations/CraftingOperation.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java
Labels: 🧹 Chores

#3921 Deobfuscate blocks when gold panning
  src/main/java/io/github/thebusybiscuit/slimefun4/integrations/OrebfuscatorIntegration.java
Labels: ✨ Fix, Build tested

#3917 Add filter to researches for sf stats completion calculation
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
Labels: ✨ Fix, Build tested
