Repository Slimefun/Slimefun4, pull requests merged in 2024-01, with the labels that each got.

#4065 Storage rewrite - Phase 1
  .adr-dir
  .gitignore
  docs/adr/0001-storage-layer.md
  docs/adr/README.md
  src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/GPSNetwork.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/Waypoint.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerBackpack.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/storage/Storage.java
  src/main/java/io/github/thebusybiscuit/slimefun4/storage/backend/legacy/LegacyStorage.java
  src/main/java/io/github/thebusybiscuit/slimefun4/storage/data/PlayerData.java
  src/test/java/io/github/thebusybiscuit/slimefun4/api/gps/TestWaypoints.java
  src/test/java/io/github/thebusybiscuit/slimefun4/api/profiles/TestPlayerBackpacks.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestBackpackListener.java
  src/test/java/io/github/thebusybiscuit/slimefun4/storage/backend/TestLegacyBackend.java
  src/test/java/io/github/thebusybiscuit/slimefun4/test/mocks/MockProfile.java
Labels: 🔧 Technical Thread, 🎈 Feature, 🔧 API, Build tested

#4077 temporarily diable senstive blocks check
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: ✨ Fix

#4081 Fix backpack IDs not incrementing
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
  src/test/java/io/github/thebusybiscuit/slimefun4/api/profiles/TestPlayerBackpacks.java
Labels: ✨ Fix

#4089 Fixes NPE when interacting with air
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunItemInteractListener.java
Labels: ✨ Fix

#4090 Fix another bug with interaction fix and add more interaction tests
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSlimefunItemInteractListener.java
Labels: 🧹 Chores

#4086 Update MockBukkit to 1.20.4 along with existing tests
  .gitignore
  docs/sop/update.md
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/FileUtils.java
  src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunBlockPlaceEvent.java
  src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
  src/test/java/io/github/thebusybiscuit/slimefun4/api/gps/TestWaypoints.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestCargoNodeListener.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSlimefunGuideListener.java
  src/test/java/io/github/thebusybiscuit/slimefun4/storage/backend/TestLegacyBackend.java
  src/test/java/io/github/thebusybiscuit/slimefun4/test/TestUtilities.java
Labels: 🧹 Chores

#4094 fix items not being able to be placed on ancient altar
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java
Labels: ✨ Fix

#4100 Update dough to fix item stacking issue
  pom.xml
Labels: ✨ Fix

#4101 fix slimefun block turning into a vanilla block if there are viewers
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSlimefunItemInteractListener.java
Labels: ✨ Fix

#4105 fix slimefun blocks turning into vanilla blocks for 1.20.1 and lower
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java
Labels: ✨ Fix

#4098 Make SlimefunItem#getOptionalByItem static like intended
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java
Labels: ✨ Fix

#4109 fix: fix spawn in ArmorStandUtils
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java
Labels: ✨ Fix
