Repository Slimefun/Slimefun4, pull requests merged in 2024-09, with the labels that each got.

#4234 Remove block info if present when placing on air (more in desc)
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
Labels: ✨ Fix, Build tested

#4230 Reduce code duplication
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricSmeltery.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOMiner.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/ChestMenuUtils.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java
Labels: 🧹 Chores

#4227 Fix setCapacity typo in a warn of AGenerator.java
  src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java
Labels: 🧹 Chores

#4238 [ci skip] fix: fix JsonParser static methods not exist before 1.18
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/MetricsService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubConnector.java
Labels: ✨ Fix

#4240 chore: various changes to 1.20.5 branch
  .github/workflows/e2e-testing.yml
  src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestMinecraftVersion.java
Labels: 🧹 Chores

#4186 Update to 1.20.5
  .github/workflows/discord-webhook.yml
  .github/workflows/e2e-testing.yml
  .github/workflows/javadocs.yml
  .github/workflows/maven-compiler.yml
  .github/workflows/publish-build.yml
  .github/workflows/pull-request.yml
  .github/workflows/sonarcloud.yml
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/gps/TeleportationManager.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/ItemGroup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItemStack.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/network/NetworkVisualizer.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/RadiationSymptom.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/MinerAndroid.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/autocrafters/AbstractAutoCrafter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/MultiTool.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/AutoBrewer.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/accelerators/AnimalGrowthAccelerator.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/accelerators/CropGrowthAccelerator.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/accelerators/TreeGrowthAccelerator.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/EnchantmentRune.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/VillagerRune.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/Bandage.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/MedicalSupply.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/Splint.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ClimbingPick.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/ExplosiveBow.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/IcyBow.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/AncientAltarTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/ArmorTask.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/FireworkUtils.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/compatibility/VersionedEnchantment.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/compatibility/VersionedEntityType.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/compatibility/VersionedItemFlag.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/compatibility/VersionedParticle.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/compatibility/VersionedPotionEffectType.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/compatibility/VersionedPotionType.java
  src/main/java/io/github/thebusybiscuit/slimefun4/utils/itemstack/ColoredFireworkStar.java
  src/test/java/io/github/thebusybiscuit/slimefun4/core/commands/TestGuideCommand.java
  src/test/java/io/github/thebusybiscuit/slimefun4/core/services/localization/AbstractLocaleRegexChecker.java
  src/test/java/io/github/thebusybiscuit/slimefun4/core/services/localization/TestColorCodes.java
  src/test/java/io/github/thebusybiscuit/slimefun4/core/services/localization/TestSlimefunSpelling.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/items/TestDamageableItem.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/TestClimbingPick.java
  src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestCoolerListener.java
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestMinecraftVersion.java
  src/test/java/io/github/thebusybiscuit/slimefun4/utils/biomes/TestBiomeMapCompatibility.java
  src/test/resources/biomes/1.20.5+.json
Labels: 🧹 Chores, 🎮 Game Update, Build tested

#4243 chore(jitpack): bump jdk version to 21
  jitpack.yml
  src/main/java/me/mrCookieSlime/Slimefun/api/BlockInfoConfig.java
Labels: 🧹 Chores

#4189 chore: localization for options menu
  src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/FireworksOption.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/GuideModeOption.java
  src/main/resources/languages/en/messages.yml
Labels: 🧹 Chores
