Repository Slimefun/Slimefun4, pull requests merged in 2024-02, with the labels that each got.

#4119 Move PlayerProfile saving off the main thread
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/SlimefunTabCompleter.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/debug/TestCase.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/AutoSavingService.java
Labels: 🧹 Chores, 💡 Performance Optimization

#4096 Add update warning to /sf versions
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/UpdaterService.java
Labels: 🧹 Chores

#4124 Fixes #4123 - Coal Generator will no longer be locked after researching
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/storage/backend/legacy/LegacyStorage.java
  src/test/java/io/github/thebusybiscuit/slimefun4/storage/backend/TestLegacyBackend.java
Labels: ✨ Fix, Build tested

#4127 Fixes exhaustion when loading large profiles
  src/main/java/io/github/thebusybiscuit/slimefun4/Threads.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
Labels: ✨ Fix

#4125 Fixes guide search when using colored chat
  pom.xml
Labels: ✨ Fix

#4067 Add new analytics service
  README.md
  src/main/java/io/github/thebusybiscuit/slimefun4/Threads.java
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/debug/TestCase.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/AnalyticsService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/ThreadService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SlimefunProfiler.java
  src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
  src/main/java/io/github/thebusybiscuit/slimefun4/storage/backend/legacy/LegacyStorage.java
  src/main/resources/config.yml
Labels: 🎈 Feature

#4134 fix dupe glitch with backpacks
  src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
Labels: ✨ Fix

#4142 update changelog && revert dependency update
  CHANGELOG.md
  pom.xml
Labels: 🧹 Chores

#4145 [ci skip] Add blob builds workflow
  .github/workflows/publish-build.yml
Labels: 🧹 Chores

#4149 [ci skip] Update release candidates file
  .github/workflows/release-candidates.yml
Labels: 🧹 Chores

#4150 Fix ToC in CHANGELOG
  CHANGELOG.md
Labels: 🧹 Chores

#4068 Remove Unirest and replace with Java's native HttpClient
  pom.xml
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/MetricsService.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/ContributionsConnector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubActivityConnector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubConnector.java
  src/main/java/io/github/thebusybiscuit/slimefun4/core/services/github/GitHubIssuesConnector.java
Labels: 🧹 Chores
